examples/database.go
examples/demo.go
go.mod
main.go
mo2.go
server/controller/account.go
server/controller/controller.go
server/webServer.go

add Swagger

---

mo2front/package-lock.json
mo2front/src/App.vue
mo2front/src/components/InputList.vue
mo2front/src/models/index.ts
mo2front/src/router/index.ts
mo2front/src/utils/index.ts
mo2front/src/views/About.vue
mo2front/src/views/Account.vue

@chronos/input list

---

.gitignore
designs/database.md

add database.md

---

.idea/.gitignore
.idea/mo2.iml
.idea/modules.xml
.idea/vcs.xml
.vscode/workspace.code-workspace
dto/account.go
dto/img.go
go.mod
go.sum
mo2front/package-lock.json
mo2front/package.json
mo2front/src/components/MO2Editor.vue
mo2front/src/models/index.ts
mo2front/src/utils/index.ts
mo2front/src/views/About.vue
mo2img/qiniu.go
mo2img/qiniu_test.go
mo2utils/auth.go
mo2utils/consts.go
server/controller/img.go
server/middleware/auth.go
server/model/account.go
server/webServer.go

done qiniu

---

mo2front/src/assets/main.scss
mo2front/src/components/MO2Dialog.vue
mo2front/src/components/MO2Editor.vue
mo2front/src/router/index.ts
mo2front/src/utils/index.ts
mo2front/src/views/EditArticle.vue
mo2front/src/views/ReadArticle.vue

done read article

---

server/controller/img.go
server/middleware/auth.go
server/webServer.go

enhance auth middleware

---

database/blogs.go
server/controller/blog.go
server/middleware/auth.go
server/model/blog.go
server/model/entity.go
server/webServer.go

讨论后确定的新的组织方法，详情看 [项目内成员可见](https://www.limfx.pro/ReadArticle/1357/db-v1)

博客与草稿的组织方法

---

database/blogs.go
database/categories.go
dto/blog.go
dto/category.go
server/controller/blog.go
server/controller/category.go
server/model/blog.go
server/model/category.go
server/webServer.go

fix #42
continue implement the initial edition of #41

Add category

---

database/accounts.go
dto/account.go
server/controller/account.go
server/model/account.go
server/webServer.go

Add userinfo

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
main.go
mo2front/src/components/BlogTimeLineList.vue
mo2front/src/components/BlogTimeLineSkeleton.vue
mo2front/src/models/index.ts
mo2front/src/utils/index.ts
mo2front/src/views/About.vue
mo2front/src/views/Home.vue
mo2front/src/views/ReadArticle.vue
mo2front/vue.config.js

- change cdn
- add home load skeleton
- add username to blog list
- done read article page

@chronos/front bugfixes

---

database/accounts.go
server/model/account.go

Fix accountbug

---

database/accounts.go
mo2utils/email.go
server/controller/account.go
services/emailService/email.go
services/emailService/email_test.go

add email rate limiter

---

server/middleware/README.md
server/middleware/auth.go
server/middleware/auth_test.go
services/emailService/email.go
services/emailService/email_test.go

add or logic to role auth middleware

---

mo2front/package-lock.json
mo2front/package.json
mo2front/src/components/ImageCropper.vue
mo2front/src/components/MO2Dialog.vue
mo2front/src/components/UserAvatar.vue
mo2front/src/models/index.ts
mo2front/src/utils/index.ts
mo2front/src/views/About.vue
mo2front/src/views/Account.vue
mo2front/src/views/EditArticle.vue
mo2front/src/views/ReadArticle.vue
updateWatcher/nginx.conf

@chronos/user edit profile front

---

database/blogs.go
mo2front/src/App.vue
mo2front/src/components/AccountModal.vue
mo2front/src/components/MO2Editor.vue
mo2front/src/components/UserAvatar.vue
mo2front/src/models/index.ts
mo2front/src/plugins/vuetify.ts
mo2front/src/utils/index.ts
mo2front/src/views/Account.vue
mo2front/src/views/EditArticle.vue
mo2front/src/views/Home.vue
mo2front/vue.config.js
server/controller/blog.go
server/model/blog.go
updateWatcher/nginx.conf

better query

---

Dockerfile
README.md
server/middleware/README.md
server/middleware/auth.go
updateWatcher/docker-compose.yml

update ratelimiter related docs

---

mo2front/src/views/Account.vue
mo2front/src/views/EditArticle.vue

fix change other's avatar

---

mo2front/src/utils/index.ts
mo2front/src/views/EditArticle.vue

前端优化md upload

---

mo2front/src/App.vue
mo2front/src/assets/main.scss
mo2front/src/views/Account.vue
mo2front/src/views/Home.vue
updateWatcher/nginx.conf

support http 2.0

---

mo2front/src/components/BlogTimeLineList.vue
mo2front/src/components/BlogTimeLineSkeleton.vue
mo2front/src/components/Category.vue
mo2front/src/components/InputList.vue
mo2front/src/components/NothingHere.vue
mo2front/src/models/index.ts
mo2front/src/utils/index.ts
mo2front/src/views/Account.vue
mo2front/src/views/EditArticle.vue

EPIC: done categories 🎉 

---

database/blogs.go
database/comment.go
database/utils.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
mo2utils/query.go
server/controller/Comment.md
server/controller/comment.go
server/controller/controller.go
server/model/comment.go
server/model/entity.go

✨ EPIC: backend article comment

---

mo2front/package-lock.json
mo2front/package.json
mo2front/src/App.vue
mo2front/src/assets/main.scss
mo2front/src/components/Category.vue
mo2front/src/main.ts
mo2front/src/models/index.ts
mo2front/src/utils/index.ts
mo2front/src/views/ReadArticle.vue

❤️  EPIC: Done frontend comment

---

mo2front/src/components/Category.vue
mo2front/src/utils/index.ts
mo2front/src/views/EditArticle.vue

🚑 Frontend fix: categories

---

mo2front/src/App.vue
mo2front/src/views/About.vue
mo2front/src/views/Home.vue

✨  Epic: About page

---

database/blogs.go
database/categories.go
database/categories_test.go
mo2front/package-lock.json
server/controller/blog.go

fix deleted blogs in category

---

database/blogs.go
database/categories_test.go
database/recycleBin.go
database/recycleBin_test.go
database/utils.go
database/utils_test.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
server/controller/blog.go
server/controller/controller.go
server/model/readme.md
server/model/recycleItem.go

Add recycle

---

mo2front/src/App.vue
mo2front/src/registerServiceWorker.ts
mo2front/src/utils/index.ts
mo2front/vue.config.js

[🐛 BUG] pwa refresh

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
mo2front/src/App.vue
mo2front/src/components/InputList.vue
mo2front/src/models/index.ts
mo2front/src/plugins/vuetify.ts
mo2front/src/router/index.ts
mo2front/src/utils/index.ts
mo2front/src/views/Account.vue
mo2front/src/views/ReadArticle.vue
mo2front/src/views/Settings.vue

💄 [Epic] Done settings page

---

database/categories.go
database/directories.go
database/directories_test.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
mo2utils/mo2errors/error.go
server/controller/account.go
server/controller/blog.go
server/controller/category.go
server/controller/controller.go
server/controller/directory.go
server/model/directory.go

增加通过列表查询directory数据

---

mo2front/src/App.vue
mo2front/src/components/BlogTimeLineList.vue
mo2front/src/models/index.ts
mo2front/src/router/index.ts
mo2front/src/utils/index.ts
mo2front/src/views/Account.vue
mo2front/src/views/Home.vue
mo2front/src/views/Notifications.vue
mo2front/src/views/Search.vue

🚀 done notification!

---

go.mod
go.sum
mo2utils/mo2errors/error.go
server/controller/blog.go
services/accessControl/grants.go
services/accessControl/grants_test.go
services/accessControl/resource.go
services/accessControl/rules.go

Use abac example

---

database/accounts.go
mo2front/package-lock.json
mo2front/package.json
mo2front/src/assets/main.scss
mo2front/src/components/AccountModal.vue
mo2front/src/components/UserAvatar.vue
mo2front/src/models/index.ts
mo2front/src/utils/index.ts
mo2front/src/views/Account.vue
mo2front/vue.config.js
server/controller/account.go
server/controller/controller.go
server/controller/oauth.go

💄 [enhance] better user profile

---

database/accounts.go
mo2front/src/components/AccountModal.vue
mo2front/src/components/UserAvatar.vue
mo2front/src/models/index.ts
mo2front/src/utils/index.ts
mo2front/src/views/Account.vue
mo2front/vue.config.js
server/controller/account.go
server/controller/controller.go
server/controller/oauth.go

💖Epic：Oauth接口 backend

---

.gitattributes
mo2front/src/components/BlogTimeLineList.vue
mo2utils/search.go
server/controller/blog.go
services/mo2search/mo2search.go
updateWatcher/docker-compose.yml

🔍 use search micro service

---

mo2front/src/App.vue
mo2front/src/assets/main.scss
mo2front/src/utils/index.ts
mo2front/src/views/ReadArticle.vue

✨ [enhancement] add toc for article

---

mo2front/src/App.vue
mo2front/src/utils/api/index.ts
mo2front/src/utils/index.ts

✨ [feat]add img upload failed prompt

---

config/config.go
config/private.go
database/accounts.go
database/blogs.go
database/categories.go
database/categories_test.go
database/comment.go
database/config.go
mo2utils/files.go
mo2utils/jwtutils.go
server/middleware/auth.go
server/webServer.go
services/accessControl/rules_test.go
services/loghelper/loghelper.go

[Fix] #259

---

server/controller/controller_test.go
server/middleware/README.md
server/middleware/auth.go
server/middleware/auth_test.go
server/webServer.go

🎉 [enhancement] better middleware api

---

go.mod
go.sum
mo2front/src/models/index.ts
mo2front/src/utils/api/index.ts
mo2front/src/utils/api/like.ts
mo2front/src/views/Account.vue
mo2front/src/views/Notifications.vue
mo2front/src/views/ReadArticle.vue
mo2front/src/views/Search.vue
mo2img/qiniu.go
mo2utils/adapter/httpadapter.go
server/controller/controller.go
server/controller/like.go
server/controller/like_test.go
server/webServer.go
services/loghelper/loghelper.go

✨ [feat] add blog like backend api

---

mo2front/public/index.html
mo2front/src/App.vue
mo2front/src/registerServiceWorker.ts
mo2front/vue.config.js

[feat] offline app support

---

mo2front/package-lock.json
mo2front/package.json
mo2front/src/App.vue
mo2front/vue.config.js

✨ [Proposal] install prompt

---

mo2front/src/App.vue
mo2front/src/assets/main.scss
mo2front/src/models/index.ts
mo2front/src/router/index.ts
mo2front/src/utils/api/index.ts
mo2front/src/views/About.vue
mo2front/src/views/PageNotFound.vue
mo2front/src/views/ReadArticle.vue
mo2front/src/views/Recycle.vue

⭐ [feat] recycle bin 

---

database/accounts.go
database/blogs.go
mo2front/package-lock.json
mo2front/package.json
mo2front/src/App.vue
mo2front/src/components/Editor/MO2Editor.vue
mo2front/src/models/index.ts
mo2front/src/utils/api/index.ts
mo2front/src/utils/index.ts
mo2front/src/views/EditArticle.vue
mo2utils/jwtutils.go
server/controller/account.go
server/controller/blog.go
server/controller/controller.go
server/model/blog.go

done most of issue281

---

database/blogs.go
database/blogs_test.go

fix bug and add test

---

database/blogs.go
database/blogs_test.go

continue fixing bug

---

database/blogs.go
dto/account.go
mo2front/src/models/index.ts
mo2front/src/utils/api/index.ts
mo2front/src/views/ReadArticle.vue
mo2utils/adapter/httpadapter.go
server/controller/controller.go
server/controller/score.go
server/model/blog.go
services/loghelper/loghelper.go

[Proposal] Score

---

database/blogs.go
database/config.go
database/project.go
database/project_test.go
database/utils.go
mo2front/package-lock.json
mo2front/src/App.vue
mo2front/src/components/MO2Dialog.vue
mo2front/src/main.ts
mo2front/src/models/index.ts
mo2front/src/router/index.ts
mo2front/src/utils/api/index.ts
mo2front/src/utils/api/project.ts
mo2front/src/utils/api/queryParser.ts
mo2front/src/utils/index.ts
mo2front/src/views/Project.vue
server/controller/blog.go
server/controller/controller.go
server/controller/project.go
server/model/blog.go

add proj backend

---

server/controller/project.go
server/controller/project_test.go

✅ [test] add project Test
